<?php
/**
 * @category   Emarsys
 * @package    Emarsys_Emarsys
 * @copyright  Copyright (c) 2017 Emarsys. (http://www.emarsys.net/)
 */

/** @var \Emarsys\Emarsys\Block\JavascriptTracking $block */
?>
<!-- This code will embeded on all pages -->
<?php if ($customerEmail = $block->getCustomerEmailAddress()): ?>
    <script>ScarabQueue.push(["setEmail", "<?php echo $customerEmail; ?>"]);</script>
<?php endif; ?>

<script>ScarabQueue.push(["cart", [<?php echo $block->getCartItemsJsonData() ?>]]);</script>

<?php if ($orders = $block->getOrderData()): ?>
<script>ScarabQueue.push(['purchase', <?php echo $orders; ?>]);</script>
<?php endif; ?>

<?php echo $this->getChildHtml('emarsys.recommendations'); ?>
<script>ScarabQueue.push(['go']);</script>
